### ISSUE TITLE
Incorrect Quotation Marks

### ISSUE THREAD

**Issue by paulwetter** [imabdk/Toast-Notification-Script#11]
Wrong type of quotation marks used in the query on line 520.
https://github.com/imabdk/Toast-Notification-Script/blob/4b6d3b8c5b49d4d93df6772229fb5228899ccaf3/New-ToastNotification.ps1#L520

**Comment by imabdk** [comment]
Wow. Well done spotted. Looks like a copy/paste thing. Fixed in the next release. Thank you.
