### ISSUE TITLE
Custom "ToastRunApplicationID:" protocol not doing anything when application InstallState is "NotUpdated"

### ISSUE THREAD

**Issue by kheldorn** [imabdk/Toast-Notification-Script#16]
While debugging why the custom "ToastRunApplicationID:" protocol wasn't doing what it was supposed to do I checked the InstallState of the application I was trying to install and found that it was "NotUpdated", rather than "Installed" or "NotInstalled", which is what the script is checking for.

Was running the following configuration:

```
	<Option Name="RunApplicationID" Enabled="True" Value="ScopeId_968C5854-F7DB-48D1-B4AA-C4DCEAE28031/Application_fc16cc10-b644-4559-96bd-432ba32d36fe" />
	<Option Name="DynamicDeadline" Enabled="True" Value="ScopeId_968C5854-F7DB-48D1-B4AA-C4DCEAE28031/Application_fc16cc10-b644-4559-96bd-432ba32d36fe" />
	<Option Name="ActionButton1" Enabled="True" />
	<Option Name="Action1" Value="ToastRunApplicationID:" />
```

I've submitted a pull request @ #15 (sorry for the additional line-ending edits. Github's webinterface forced those on me. Feel free to ignore those.) The truly important edit is in line 1093.

**Comment by imabdk** [comment]
Good catch. As mentioned in the pull request, I'm fixing this in the next release. Thank you!
