### ISSUE TITLE
User can disable notifications for specific sender

### ISSUE THREAD

**Issue by Maneridiet** [imabdk/Toast-Notification-Script#18]
It is possible to disable the notifications for Softwarecenter or Powershell using the sender notification settings or "Turn off all notifications setting" of the Notification Center.  You can see the registry keys beeing reset after the next run of the Toast-Notification-Script, but this does not affect the visibility of the notifications. No reboot or service restart can fix this issue. The only way to turn the notifications back on is by using the On/Off Switch in the sender notification settings.

**Comment by imabdk** [comment]
Yeah, I know that. The built-in functionality I offer only prevents that one option from being disabled. There are other means though in completely disabling the user's options to disable the notification. I mention that in the end of this post: https://www.imab.dk/windows-10-toast-notification-script-update-second-action-button-and-built-in-prevention-from-disabling-toast-notifications/
