### ISSUE TITLE
Testing OSUpgrades with Update ID - Software Center not launching

### ISSUE THREAD

**Issue by sammons86** [imabdk/Toast-Notification-Script#23]
Looks like the if condition on 909 is using a test update ID variable
If I switch $TestUpdateID to $UpdateID it works a charm,

Thank you for your continued work on this!
Mike.

**Comment by sammons86** [comment]
Scrap that, I realise that the $TestUpdateID variable is actually used to query the update in WMI. 

I have the 20H2 feature update deployed to a machine as available and it's visible in software center,
I have set the KB number in the osupgrade.xml file 
I hit the install button on the Toast Notification for OS upgrade
log confirms the update was found and the full name is visible in the log.
The log tells me Get-CMUpdate was successfully run and UpdateID retrieved
Writing the UpdateID to the registry also succeeds.
The toast notification appears and I click the install now option
I can see the momentary flash of the command dialogue window which I think is ToastRunUpdateID.cmd being executed but the software centre never starts.

Using a packageID the software center does load and navigates to the OSD tab and starts the package ID specified,
initially I thought the $TestUpdateID was behind this.

**Comment by sammons86** [comment]
*FacePalm* 
Resolved by adding ToastRunUpdateID to Action1 in OSUpgrade.xml
<Option Name="Action1" Value="ToastRunUpdateID:" />

**Comment by imabdk** [comment]
Ah, thank you for confirming that everything worked out OK. I would think I had tested this multiple times before releasing :-)

**Comment by sammons86** [comment]
No worries, I jumped from 1.4.2 to 2.1.0 and didn't do much reading :D 
One thing I think it used to do... I could be remembering wrong, if you click the body of the notification is just dismisses the notification,
Can that be changed so clicking the body of the notification launches software center, or follows the same as the action button ?
