### ISSUE TITLE
Applocker and running the script in user context

### ISSUE THREAD

**Issue by Alslinet** [imabdk/Toast-Notification-Script#27]
I wanted to run the script in user context but i am getting issues with it running side by side with applocker. Having the username inside ToastRunApplicationID.cmd makes the file unique on each computer and that way there is no way for us to securely whitelist the file. As we would need a seperate file hash for every single user in the company. Would it be possible to at least make sure these files are the same on every machine? Either by providing the username as a parameter or making the cmd file lookup the username itself?
![image](https://user-images.githubusercontent.com/2192480/117635957-a198ad80-b180-11eb-9995-013f0427b331.png)

Also yes we will try running the 2.2 version in system context for now, I just wanted to report this issue, in case its fixable.

**Comment by imabdk** [comment]
If you disable the CreateScriptsAndProtocols option in the config.xml in general, the script won't create the custom scripts for you. In this scenario, you will be able to create the scripts yourself and distribute with whatever method you like. This will keep the hashes for your AppLocker rules :-)
