### ISSUE TITLE
CustomAudio

### ISSUE THREAD

**Issue by ConfigConfused** [imabdk/Toast-Notification-Script#4]
CustomAudio = $True section is broken.

Invoke-Command -ScriptBlock {
				Add-Type -AssemblyName System.Speech
				$speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
				sleep 1.25
				$speak.SelectVoiceByHints("female",65)
				$speak.Speak($CustomAudioTextToSpeech)
				$speak.Dispose()
			}    

Needs to be moved to the try section of function Display-ToastNotification() 
Line 693

Added sleep to prevent audio from overlapping notification chime.

**Comment by imabdk** [comment]
Thank you for this. I will look into this asap. It probably happened when I did the new function. I never really used the audio option and I initially just added it for fun a giggles. Will fix asap. Thanks again. :-)

**Comment by imabdk** [comment]
This is fixed in a new version I'm probably releasing tomorrow (if I get to get the blog post ready). Thanks again :-)
