### ISSUE TITLE
Notification for win10 upgrade scenario displays "Dismiss"  button even when disabled in the XML

### ISSUE THREAD

**Issue by MaartenPauchet** [imabdk/Toast-Notification-Script#5]
Hi,

I've noticed that the 2.0.2 is displaying a Dismiss button even though it is disabled in the XML.
I checked the log file and there I also see the line : Creating the xml for no dismiss button.

I changed it around and removed the snooze button, keeping only the action + dismiss button. that works. 

So it's reading the XML and interpreting the config, yet it's still displaying the button.

`2020-10-05 14:02:08 INFO: Creating the xml for no dismiss button
2020-10-05 14:02:08 INFO: Creating the xml for snooze button
2020-10-05 14:02:08 INFO: Toast notification is used in regards to OS upgrade. Taking running OS build into account
2020-10-05 14:02:08 INFO: All good. Toast notification was displayed`

the config.xml file without language part:
`<?xml version="1.0" encoding="utf-8"?>
<Configuration>
	<Feature Name="Toast" Enabled="True" /> 
	<Feature Name="UpgradeOS" Enabled="True" />	
	<Feature Name="PendingRebootUptime" Enabled="False" />	
	<Feature Name="PendingRebootCheck" Enabled="False" />	
	<Feature Name="ADPasswordExpiration" Enabled="False" />	
	<Option Name="TargetOS" Build="18363" />	
	<Option Name="MaxUptimeDays" Value="-6" />	
	<Option Name="PendingRebootUptimeText" Enabled="False" />	
	<Option Name="PendingRebootCheckText" Enabled="False" />	
	<Option Name="ADPasswordExpirationText" Enabled="False" />	
	<Option Name="ADPasswordExpirationDays" Value="90" />	
	<Option Name="RunPackageID" Enabled="false" Value="" /> 
	<Option Name="RunApplicationID" Enabled="False" Value="ScopeId_A9117680-D054-482B-BC97-532E6CBD0E6B/Application_fd55f35c-4e34-4490-a3ec-ee0b79233ec6" /> 
	<Option Name="RunUpdateID" Enabled="False" Value="4561600" /> 
	<Option Name="RunUpdateTitle" Enabled="False" Value="" /> 
	<Option Name="Deadline" Enabled="False" Value="30-09-2019 08:00" />	
	<Option Name="DynamicDeadline" Enabled="False" Value="" />	
	<Option Name="CreateScriptsAndProtocols" Enabled="True" /> 
	<Option Name="UseSoftwareCenterApp" Enabled="True" />	
	<Option Name="UsePowershellApp" Enabled="False" />	
	<Option Name="CustomAudio" Enabled="False" />	
	<Option Name="LogoImageName" Value="ToastLogoImageTSI.jpg" />  
	<Option Name="HeroImageName" Value="ToastHeroImageWaas.jpg" /> 	
	<Option Name="ActionButton" Enabled="True" />	
	<Option Name="DismissButton" Enabled="False" />	
	<Option Name="SnoozeButton" Enabled="True" /> 
	<Option Name="Scenario" Type="reminder" />	
	<Option Name="Action" Value="softwarecenter:Page=OSD" />	
	<Text Option="GreetGivenName" Enabled="True" />	
	<Text Option="MultiLanguageSupport" Enabled="False" /> 
	<en-US>`

**Comment by matbe** [comment]
You have enabled the snooze button in the XML above and just as it says in the configfile that will enable the dismiss button.

<Option Name="SnoozeButton" Enabled="True" />  

So that is by design I would say.

**Comment by imabdk** [comment]
Right, Matt is correct. When formatting the XLM content I just found it easier to always have all buttons when enabling the snooze option. Also, I never really found a need for not having the dismiss button.
