### ISSUE TITLE
Buttons disappear if PendingRebootUptimeText=True

### ISSUE THREAD

**Issue by matbe** [imabdk/Toast-Notification-Script#7]
If using the PendingRebootUptimeText=True option the extra text causes the buttons to disappear.

With PendingRebootUptimeText=False
![ToastReboot1](https://user-images.githubusercontent.com/15101419/96879667-9bf5a780-147c-11eb-8236-fe0a9ea32271.png)

With PendingRebootUptimeText=True
![ToastReboot2](https://user-images.githubusercontent.com/15101419/96879728-add74a80-147c-11eb-8e5c-411988cdc989.png)

The issue can be resolved by changeing the code on row 1910 from:
```powershell 
if (($PendingRebootUptimeTextEnabled -eq "True") -AND ($Uptime -gt $MaxUptimeDays)) {
$UptimeGroup = @"
        <group>
            <subgroup>     
                <text hint-style="body" hint-wrap="true" >$PendingRebootUptimeTextValue</text>
            </subgroup>
        </group>
        <group>
            <subgroup>
                <text hint-style="base" hint-align="left">$ComputerUptimeText $Uptime $ComputerUptimeDaysText</text>
            </subgroup>
        </group>
"@
    $Toast.toast.visual.binding.InnerXml = $Toast.toast.visual.binding.InnerXml + $UptimeGroup
}
```

to:
```powershell
if (($PendingRebootUptimeTextEnabled -eq "True") -AND ($Uptime -gt $MaxUptimeDays)) {
$UptimeGroup = @"
        <group>
            <subgroup>     
                <text hint-style="body" hint-wrap="true" >$PendingRebootUptimeTextValue</text>
                <text hint-style="body" hint-wrap="true" ></text>
                <text hint-style="base" hint-align="left">$ComputerUptimeText $Uptime $ComputerUptimeDaysText</text>
            </subgroup>
        </group>
"@
    $Toast.toast.visual.binding.InnerXml = $Toast.toast.visual.binding.InnerXml + $UptimeGroup
}
```

This will give the same visual apperance of the text and allow the buttons to be displayed. I do not know why this happens, I havn't found any documented limits to the number of groups within an XML but I am suspecting that might be the issue.

I have tested on Windows 10 1909 and 2004 and replicated the issue on both.

**Comment by matbe** [comment]
This might be related:
[https://social.msdn.microsoft.com/Forums/windows/en-US/f0e21a2d-0c67-4da2-a90e-ff27fef7be88/uwplength-limits-to-number-of-lines-and-characters-displayed-in-adaptive-toasts?forum=wpdevelop](https://social.msdn.microsoft.com/Forums/windows/en-US/f0e21a2d-0c67-4da2-a90e-ff27fef7be88/uwplength-limits-to-number-of-lines-and-characters-displayed-in-adaptive-toasts?forum=wpdevelop)

_Toasts can only have up to 3 text elements_

**Comment by imabdk** [comment]
Yeah, I've noticed the same, and my conclusion is similar; there's a limit of how much content the toast can have in terms of groups. I'll try to prevent that combination instead. Thanks :-)
