### ISSUE TITLE
Feature - Announcements / Question

### ISSUE THREAD

**Issue by RickBankers** [imabdk/Toast-Notification-Script#8]
Feature - Announcements
I really like your toast script and I was wondering if there was a way to add just plain notifications. I'd like to be able to have the script check a URL for the xml for a general announcement. I'd also want to make sure users aren't shown the announcement more than once each time the xml is updated.

Question
I see you're writing data to the HKCU registry and to the log. Doesn't that bloat the registry and log after a while or is there some cleanup done to those items so they don't get bloated over time. Ideally a rolling log and registry entries would be great!

Thanks again for writing this! It's amazing!

**Comment by imabdk** [comment]
To answer your question, no the log file gets overwritten if and when it reaches 5MB. Also, the registry is limited to 3 values currently. I'm reusing the same keys over and over again, just with new values. No bloat will ever happen.

I'm not sure I understand your request in regards to announcements. Can you elaborate some more? :-)

**Comment by RickBankers** [comment]
Thanks for responding. I have the script running as a scheduled task powershell script running every 15 minutes. When I send out a new notification I'd like each user to only see it once. If they've seen and acknowledged it previously I don't want it to re-appear the next time the script runs. Otherwise people are getting nagged every 15 minutes with the same notification they already seen.

**Comment by imabdk** [comment]
Right, this RunOnce behavior is something I will implement very soon. Thank you! :-)
